export const launches = [
  {
    fairings: {
      reused: false,
      recovery_attempt: false,
      recovered: false,
      ships: [],
    },
    links: {
      patch: {
        small: "https://images2.imgbox.com/3c/0e/T8iJcSN3_o.png",
        large: "https://images2.imgbox.com/40/e3/GypSkayF_o.png",
      },
      reddit: {
        campaign: null,
        launch: null,
        media: null,
        recovery: null,
      },
      flickr: {
        small: [],
        original: [],
      },
      presskit: null,
      webcast: "https://www.youtube.com/watch?v=0a_00nJ_Y88",
      youtube_id: "0a_00nJ_Y88",
      article:
        "https://www.space.com/2196-spacex-inaugural-falcon-1-rocket-lost-launch.html",
      wikipedia: "https://en.wikipedia.org/wiki/DemoSat",
    },
    static_fire_date_utc: "2006-03-17T00:00:00.000Z",
    static_fire_date_unix: 1142553600,
    tbd: false,
    net: false,
    window: 0,
    rocket: "5e9d0d95eda69955f709d1eb",
    success: false,
    details: "Engine failure at 33 seconds and loss of vehicle",
    crew: [],
    ships: [],
    capsules: [],
    payloads: ["5eb0e4b5b6c3bb0006eeb1e1"],
    launchpad: "5e9e4502f5090995de566f86",
    auto_update: true,
    launch_library_id: null,
    failures: [
      {
        time: 33,
        altitude: null,
        reason: "merlin engine failure",
      },
    ],
    flight_number: 1,
    name: "FalconSat",
    date_utc: "2006-03-24T22:30:00.000Z",
    date_unix: 1143239400,
    date_local: "2006-03-25T10:30:00+12:00",
    date_precision: "hour",
    upcoming: false,
    cores: [
      {
        core: "5e9e289df35918033d3b2623",
        flight: 1,
        gridfins: false,
        legs: false,
        reused: false,
        landing_attempt: false,
        landing_success: null,
        landing_type: null,
        landpad: null,
      },
    ],
    id: "5eb87cd9ffd86e000604b32a",
  },
  {
    fairings: {
      reused: false,
      recovery_attempt: false,
      recovered: false,
      ships: [],
    },
    links: {
      patch: {
        small: "https://images2.imgbox.com/4f/e3/I0lkuJ2e_o.png",
        large: "https://images2.imgbox.com/be/e7/iNqsqVYM_o.png",
      },
      reddit: {
        campaign: null,
        launch: null,
        media: null,
        recovery: null,
      },
      flickr: {
        small: [],
        original: [],
      },
      presskit: null,
      webcast: "https://www.youtube.com/watch?v=Lk4zQ2wP-Nc",
      youtube_id: "Lk4zQ2wP-Nc",
      article:
        "https://www.space.com/3590-spacex-falcon-1-rocket-fails-reach-orbit.html",
      wikipedia: "https://en.wikipedia.org/wiki/DemoSat",
    },
    static_fire_date_utc: null,
    static_fire_date_unix: null,
    tbd: false,
    net: false,
    window: 0,
    rocket: "5e9d0d95eda69955f709d1eb",
    success: false,
    details:
      "Successful first stage burn and transition to second stage, maximum altitude 289 km, Premature engine shutdown at T+7 min 30 s, Failed to reach orbit, Failed to recover first stage",
    crew: [],
    ships: [],
    capsules: [],
    payloads: ["5eb0e4b6b6c3bb0006eeb1e2"],
    launchpad: "5e9e4502f5090995de566f86",
    auto_update: true,
    launch_library_id: null,
    failures: [
      {
        time: 301,
        altitude: 289,
        reason: "harmonic oscillation leading to premature engine shutdown",
      },
    ],
    flight_number: 2,
    name: "DemoSat",
    date_utc: "2007-03-21T01:10:00.000Z",
    date_unix: 1174439400,
    date_local: "2007-03-21T13:10:00+12:00",
    date_precision: "hour",
    upcoming: false,
    cores: [
      {
        core: "5e9e289ef35918416a3b2624",
        flight: 1,
        gridfins: false,
        legs: false,
        reused: false,
        landing_attempt: false,
        landing_success: null,
        landing_type: null,
        landpad: null,
      },
    ],
    id: "5eb87cdaffd86e000604b32b",
  },
  {
    fairings: {
      reused: false,
      recovery_attempt: false,
      recovered: false,
      ships: [],
    },
    links: {
      patch: {
        small: "https://images2.imgbox.com/3d/86/cnu0pan8_o.png",
        large: "https://images2.imgbox.com/4b/bd/d8UxLh4q_o.png",
      },
      reddit: {
        campaign: null,
        launch: null,
        media: null,
        recovery: null,
      },
      flickr: {
        small: [],
        original: [],
      },
      presskit: null,
      webcast: "https://www.youtube.com/watch?v=v0w9p3U8860",
      youtube_id: "v0w9p3U8860",
      article:
        "http://www.spacex.com/news/2013/02/11/falcon-1-flight-3-mission-summary",
      wikipedia: "https://en.wikipedia.org/wiki/Trailblazer_(satellite)",
    },
    static_fire_date_utc: null,
    static_fire_date_unix: null,
    tbd: false,
    net: false,
    window: 0,
    rocket: "5e9d0d95eda69955f709d1eb",
    success: false,
    details:
      "Residual stage 1 thrust led to collision between stage 1 and stage 2",
    crew: [],
    ships: [],
    capsules: [],
    payloads: ["5eb0e4b6b6c3bb0006eeb1e3", "5eb0e4b6b6c3bb0006eeb1e4"],
    launchpad: "5e9e4502f5090995de566f86",
    auto_update: true,
    launch_library_id: null,
    failures: [
      {
        time: 140,
        altitude: 35,
        reason:
          "residual stage-1 thrust led to collision between stage 1 and stage 2",
      },
    ],
    flight_number: 3,
    name: "Trailblazer",
    date_utc: "2008-08-03T03:34:00.000Z",
    date_unix: 1217734440,
    date_local: "2008-08-03T15:34:00+12:00",
    date_precision: "hour",
    upcoming: false,
    cores: [
      {
        core: "5e9e289ef3591814873b2625",
        flight: 1,
        gridfins: false,
        legs: false,
        reused: false,
        landing_attempt: false,
        landing_success: null,
        landing_type: null,
        landpad: null,
      },
    ],
    id: "5eb87cdbffd86e000604b32c",
  },
  {
    fairings: {
      reused: false,
      recovery_attempt: false,
      recovered: false,
      ships: [],
    },
    links: {
      patch: {
        small: "https://images2.imgbox.com/e9/c9/T8CfiSYb_o.png",
        large: "https://images2.imgbox.com/e0/a7/FNjvKlXW_o.png",
      },
      reddit: {
        campaign: null,
        launch: null,
        media: null,
        recovery: null,
      },
      flickr: {
        small: [],
        original: [],
      },
      presskit: null,
      webcast: "https://www.youtube.com/watch?v=dLQ2tZEH6G0",
      youtube_id: "dLQ2tZEH6G0",
      article: "https://en.wikipedia.org/wiki/Ratsat",
      wikipedia: "https://en.wikipedia.org/wiki/Ratsat",
    },
    static_fire_date_utc: "2008-09-20T00:00:00.000Z",
    static_fire_date_unix: 1221868800,
    tbd: false,
    net: false,
    window: 0,
    rocket: "5e9d0d95eda69955f709d1eb",
    success: true,
    details:
      "Ratsat was carried to orbit on the first successful orbital launch of any privately funded and developed, liquid-propelled carrier rocket, the SpaceX Falcon 1",
    crew: [],
    ships: [],
    capsules: [],
    payloads: ["5eb0e4b7b6c3bb0006eeb1e5"],
    launchpad: "5e9e4502f5090995de566f86",
    auto_update: true,
    launch_library_id: null,
    failures: [],
    flight_number: 4,
    name: "RatSat",
    date_utc: "2008-09-28T23:15:00.000Z",
    date_unix: 1222643700,
    date_local: "2008-09-28T11:15:00+12:00",
    date_precision: "hour",
    upcoming: false,
    cores: [
      {
        core: "5e9e289ef3591855dc3b2626",
        flight: 1,
        gridfins: false,
        legs: false,
        reused: false,
        landing_attempt: false,
        landing_success: null,
        landing_type: null,
        landpad: null,
      },
    ],
    id: "5eb87cdbffd86e000604b32d",
  },
  {
    fairings: {
      reused: false,
      recovery_attempt: false,
      recovered: false,
      ships: [],
    },
    links: {
      patch: {
        small: "https://images2.imgbox.com/a7/ba/NBZSw3Ho_o.png",
        large: "https://images2.imgbox.com/8d/fc/0qdZMWWx_o.png",
      },
      reddit: {
        campaign: null,
        launch: null,
        media: null,
        recovery: null,
      },
      flickr: {
        small: [],
        original: [],
      },
      presskit:
        "http://www.spacex.com/press/2012/12/19/spacexs-falcon-1-successfully-delivers-razaksat-satellite-orbit",
      webcast: "https://www.youtube.com/watch?v=yTaIDooc8Og",
      youtube_id: "yTaIDooc8Og",
      article: "http://www.spacex.com/news/2013/02/12/falcon-1-flight-5",
      wikipedia: "https://en.wikipedia.org/wiki/RazakSAT",
    },
    static_fire_date_utc: null,
    static_fire_date_unix: null,
    tbd: false,
    net: false,
    window: 0,
    rocket: "5e9d0d95eda69955f709d1eb",
    success: true,
    details: null,
    crew: [],
    ships: [],
    capsules: [],
    payloads: ["5eb0e4b7b6c3bb0006eeb1e6"],
    launchpad: "5e9e4502f5090995de566f86",
    auto_update: true,
    launch_library_id: null,
    failures: [],
    flight_number: 5,
    name: "RazakSat",
    date_utc: "2009-07-13T03:35:00.000Z",
    date_unix: 1247456100,
    date_local: "2009-07-13T15:35:00+12:00",
    date_precision: "hour",
    upcoming: false,
    cores: [
      {
        core: "5e9e289ef359184f103b2627",
        flight: 1,
        gridfins: false,
        legs: false,
        reused: false,
        landing_attempt: false,
        landing_success: null,
        landing_type: null,
        landpad: null,
      },
    ],
    id: "5eb87cdcffd86e000604b32e",
  },
  {
    fairings: {
      reused: null,
      recovery_attempt: null,
      recovered: null,
      ships: [],
    },
    links: {
      patch: {
        small: "https://images2.imgbox.com/5c/36/gbDKf6Y7_o.png",
        large: "https://images2.imgbox.com/d6/12/yxne8mMD_o.png",
      },
      reddit: {
        campaign: null,
        launch: null,
        media: null,
        recovery: null,
      },
      flickr: {
        small: [],
        original: [],
      },
      presskit:
        "http://forum.nasaspaceflight.com/index.php?action=dlattach;topic=21869.0;attach=230821",
      webcast: "https://www.youtube.com/watch?v=nxSxgBKlYws",
      youtube_id: "nxSxgBKlYws",
      article: "http://www.spacex.com/news/2013/02/12/falcon-9-flight-1",
      wikipedia:
        "https://en.wikipedia.org/wiki/Dragon_Spacecraft_Qualification_Unit",
    },
    static_fire_date_utc: "2010-03-13T00:00:00.000Z",
    static_fire_date_unix: 1268438400,
    tbd: false,
    net: false,
    window: 0,
    rocket: "5e9d0d95eda69973a809d1ec",
    success: true,
    details: null,
    crew: [],
    ships: [],
    capsules: [],
    payloads: ["5eb0e4b7b6c3bb0006eeb1e7"],
    launchpad: "5e9e4501f509094ba4566f84",
    auto_update: true,
    launch_library_id: null,
    failures: [],
    flight_number: 6,
    name: "Falcon 9 Test Flight",
    date_utc: "2010-06-04T18:45:00.000Z",
    date_unix: 1275677100,
    date_local: "2010-06-04T14:45:00-04:00",
    date_precision: "hour",
    upcoming: false,
    cores: [
      {
        core: "5e9e289ef359185f2b3b2628",
        flight: 1,
        gridfins: false,
        legs: false,
        reused: false,
        landing_attempt: false,
        landing_success: null,
        landing_type: null,
        landpad: null,
      },
    ],
    id: "5eb87cddffd86e000604b32f",
  },
  {
    fairings: null,
    links: {
      patch: {
        small: "https://images2.imgbox.com/d9/3e/FfrN88ry_o.png",
        large: "https://images2.imgbox.com/00/2f/FhtEd0nB_o.png",
      },
      reddit: {
        campaign: null,
        launch: null,
        media: null,
        recovery: null,
      },
      flickr: {
        small: [],
        original: [],
      },
      presskit: "http://www.spacex.com/files/downloads/cots1-20101206.pdf",
      webcast: "https://www.youtube.com/watch?v=cdLITgWKe_0",
      youtube_id: "cdLITgWKe_0",
      article: "https://en.wikipedia.org/wiki/SpaceX_COTS_Demo_Flight_1",
      wikipedia: "https://en.wikipedia.org/wiki/SpaceX_COTS_Demo_Flight_1",
    },
    static_fire_date_utc: "2010-12-04T00:00:00.000Z",
    static_fire_date_unix: 1291420800,
    tbd: false,
    net: false,
    window: 0,
    rocket: "5e9d0d95eda69973a809d1ec",
    success: true,
    details: null,
    crew: [],
    ships: ["5ea6ed2d080df4000697c901"],
    capsules: ["5e9e2c5bf35918ed873b2664"],
    payloads: ["5eb0e4b9b6c3bb0006eeb1e8", "5eb0e4b9b6c3bb0006eeb1e9"],
    launchpad: "5e9e4501f509094ba4566f84",
    auto_update: true,
    launch_library_id: null,
    failures: [],
    flight_number: 7,
    name: "COTS 1",
    date_utc: "2010-12-08T15:43:00.000Z",
    date_unix: 1291822980,
    date_local: "2010-12-08T11:43:00-04:00",
    date_precision: "hour",
    upcoming: false,
    cores: [
      {
        core: "5e9e289ef35918187c3b2629",
        flight: 1,
        gridfins: false,
        legs: false,
        reused: false,
        landing_attempt: false,
        landing_success: null,
        landing_type: null,
        landpad: null,
      },
    ],
    id: "5eb87cdeffd86e000604b330",
  },
  {
    fairings: null,
    links: {
      patch: {
        small: "https://images2.imgbox.com/fc/7a/r9ITwL12_o.png",
        large: "https://images2.imgbox.com/2b/8e/MYyHbnd2_o.png",
      },
      reddit: {
        campaign: null,
        launch: null,
        media: null,
        recovery: null,
      },
      flickr: {
        small: [],
        original: [],
      },
      presskit: "https://www.nasa.gov/pdf/649910main_cots2_presskit_051412.pdf",
      webcast: "https://www.youtube.com/watch?v=tpQzDbAY7yI",
      youtube_id: "tpQzDbAY7yI",
      article: "https://en.wikipedia.org/wiki/Dragon_C2%2B",
      wikipedia: "https://en.wikipedia.org/wiki/Dragon_C2%2B",
    },
    static_fire_date_utc: "2012-04-30T00:00:00.000Z",
    static_fire_date_unix: 1335744000,
    tbd: false,
    net: false,
    window: 0,
    rocket: "5e9d0d95eda69973a809d1ec",
    success: true,
    details:
      "Launch was scrubbed on first attempt, second launch attempt was successful",
    crew: [],
    ships: ["5ea6ed2d080df4000697c901"],
    capsules: ["5e9e2c5bf3591882af3b2665"],
    payloads: ["5eb0e4bab6c3bb0006eeb1ea"],
    launchpad: "5e9e4501f509094ba4566f84",
    auto_update: true,
    launch_library_id: null,
    failures: [],
    flight_number: 8,
    name: "COTS 2",
    date_utc: "2012-05-22T07:44:00.000Z",
    date_unix: 1335944640,
    date_local: "2012-05-22T03:44:00-04:00",
    date_precision: "hour",
    upcoming: false,
    cores: [
      {
        core: "5e9e289ef35918f39c3b262a",
        flight: 1,
        gridfins: false,
        legs: false,
        reused: false,
        landing_attempt: false,
        landing_success: null,
        landing_type: null,
        landpad: null,
      },
    ],
    id: "5eb87cdfffd86e000604b331",
  },
  {
    fairings: null,
    links: {
      patch: {
        small: "https://images2.imgbox.com/0b/33/2eLGEejP_o.png",
        large: "https://images2.imgbox.com/52/09/eNvilptL_o.png",
      },
      reddit: {
        campaign: null,
        launch: null,
        media: null,
        recovery: null,
      },
      flickr: {
        small: [],
        original: [],
      },
      presskit: "https://www.nasa.gov/pdf/694166main_SpaceXCRS-1PressKit.pdf",
      webcast: "https://www.youtube.com/watch?v=-Vk3hiV_zXU",
      youtube_id: "-Vk3hiV_zXU",
      article:
        "https://www.nasa.gov/mission_pages/station/main/spacex-crs1-target.html",
      wikipedia: "https://en.wikipedia.org/wiki/SpaceX_CRS-1",
    },
    static_fire_date_utc: "2012-09-29T00:00:00.000Z",
    static_fire_date_unix: 1348876800,
    tbd: false,
    net: false,
    window: 0,
    rocket: "5e9d0d95eda69973a809d1ec",
    success: true,
    details:
      "CRS-1 successful, but the secondary payload was inserted into abnormally low orbit and lost due to Falcon 9 boost stage engine failure, ISS visiting vehicle safety rules, and the primary payload owner's contractual right to decline a second ignition of the second stage under some conditions.",
    crew: [],
    ships: ["5ea6ed2d080df4000697c902"],
    capsules: ["5e9e2c5bf3591835983b2666"],
    payloads: ["5eb0e4bab6c3bb0006eeb1eb", "5eb0e4bab6c3bb0006eeb1ec"],
    launchpad: "5e9e4501f509094ba4566f84",
    auto_update: true,
    launch_library_id: null,
    failures: [],
    flight_number: 9,
    name: "CRS-1",
    date_utc: "2012-10-08T00:35:00.000Z",
    date_unix: 1349656500,
    date_local: "2012-10-08T20:35:00-04:00",
    date_precision: "hour",
    upcoming: false,
    cores: [
      {
        core: "5e9e289ff3591821a73b262b",
        flight: 1,
        gridfins: false,
        legs: false,
        reused: false,
        landing_attempt: false,
        landing_success: null,
        landing_type: null,
        landpad: null,
      },
    ],
    id: "5eb87ce0ffd86e000604b332",
  },
  {
    fairings: null,
    links: {
      patch: {
        small: "https://images2.imgbox.com/1b/b6/Z4oktZeR_o.png",
        large: "https://images2.imgbox.com/ef/39/FyZRYeOh_o.png",
      },
      reddit: {
        campaign: null,
        launch:
          "https://www.reddit.com/r/space/comments/19gm5f/live_coverage_spacex_crs2_launch_to_the_iss/c8nvah4",
        media: null,
        recovery: null,
      },
      flickr: {
        small: [],
        original: [],
      },
      presskit:
        "https://www.nasa.gov/sites/default/files/files/Orb2_PRESS_KIT.pdf",
      webcast: "https://www.youtube.com/watch?v=ik0ElKl5kW4",
      youtube_id: "ik0ElKl5kW4",
      article: "https://en.wikipedia.org/wiki/SpaceX_CRS-2",
      wikipedia: "https://en.wikipedia.org/wiki/SpaceX_CRS-2",
    },
    static_fire_date_utc: "2013-02-25T18:30:00.000Z",
    static_fire_date_unix: 1361817000,
    tbd: false,
    net: false,
    window: 0,
    rocket: "5e9d0d95eda69973a809d1ec",
    success: true,
    details: "Last launch of the original Falcon 9 v1.0 launch vehicle",
    crew: [],
    ships: ["5ea6ed2d080df4000697c902"],
    capsules: ["5e9e2c5bf359189ef23b2667"],
    payloads: ["5eb0e4bbb6c3bb0006eeb1ed"],
    launchpad: "5e9e4501f509094ba4566f84",
    auto_update: true,
    launch_library_id: null,
    failures: [],
    flight_number: 10,
    name: "CRS-2",
    date_utc: "2013-03-01T19:10:00.000Z",
    date_unix: 1362165000,
    date_local: "2013-03-01T15:10:00-04:00",
    date_precision: "hour",
    upcoming: false,
    cores: [
      {
        core: "5e9e289ff3591884e03b262c",
        flight: 1,
        gridfins: false,
        legs: false,
        reused: false,
        landing_attempt: false,
        landing_success: null,
        landing_type: null,
        landpad: null,
      },
    ],
    id: "5eb87ce1ffd86e000604b333",
  },
];

export const pastLauches = {
  docs: launches,
  totalDocs: 10,
  offset: 0,
  limit: 10,
  totalPages: 1,
  page: 1,
  pagingCounter: 1,
  hasPrevPage: false,
  hasNextPage: false,
  prevPage: null,
  nextPage: null,
};
