export default Object.freeze({
  FETCH_LAUNCHES: 'FETCH_LAUNCHES',
  NEXT_PAGE: 'NEXT_PAGE',
  PREVIOUS_PAGE: 'PREVIOUS_PAGE',
  SET_LOADING: 'SET_LOADING',
  SEARCH_LAUNCHES: 'SEARCH_LAUNCHES',
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',
});